[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
ignored_warnings_from = ["./test"]
[fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
